---
ntfy_stack_name: ntfy
ntfy_config_folder: '{{ docker_config_dir }}/{{ ntfy_stack_name }}'
ntfy_docker_volumes:
  cache: '{{ docker_volumes_dir }}/{{ ntfy_stack_name }}/cache'
  users: '{{ docker_volumes_dir }}/{{ ntfy_stack_name }}/users'
