---
grafana_stack_name: grafana
grafana_config_folders:
  provisioning: '{{ docker_config_dir }}/{{ grafana_stack_name }}/provisioning'
grafana_docker_volumes:
  data: '{{ docker_volumes_dir }}/{{ grafana_stack_name }}/data'
grafana_port: 3000
