---
- name: Set ownership variables for docker compose
  ansible.builtin.set_fact:
    docker_compose_owner: "{{ docker_compose_user_name | default(users.app_user.name) }}"
    docker_compose_group: "{{ docker_compose_user_group | default(users.app_user.group) }}"
  become: true

- name: Create volume directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: '{{ docker_compose_owner }}'
    group: '{{ docker_compose_group }}'
    mode: '0750'
  become: true
  loop: '{{ docker_compose_volumes }}'

- name: Create subdirectory for the compose file
  ansible.builtin.file:
    path: '{{ docker_compose_config_dir }}'
    state: directory
    owner: '{{ docker_compose_owner }}'
    group: '{{ docker_compose_group }}'
    mode: '0750'
  become: true

- name: Get UID and GID of app_user
  ansible.builtin.getent:
    database: passwd
    key: "{{ users.app_user.name }}"
  when: >-
    docker_compose_uid is not defined
    or docker_compose_gid is not defined

- name: Set UID and GID in variables
  ansible.builtin.set_fact:
    docker_compose_uid: "{{ ansible_facts.getent_passwd[users.app_user.name][1] }}"
    docker_compose_gid: "{{ ansible_facts.getent_passwd[users.app_user.name][2] }}"
  when: >-
    docker_compose_uid is not defined
    or docker_compose_gid is not defined

- name: Copy compose file
  ansible.builtin.template:
    src: 'compose.yaml.j2'
    dest: '{{ docker_compose_config_dir }}/compose.yaml'
    owner: '{{ docker_compose_owner }}'
    group: '{{ docker_compose_group }}'
    mode: '0640'
  become: true

- name: Copy .env file
  ansible.builtin.template:
    src: '.env.j2'
    dest: '{{ docker_compose_config_dir }}/.env'
    owner: '{{ docker_compose_owner }}'
    group: '{{ docker_compose_group }}'
    mode: '0600'
  become: true
  when:
    - docker_compose_use_env is defined
    - docker_compose_use_env | bool

- name: Start services
  community.docker.docker_compose_v2:
    project_src: '{{ docker_compose_config_dir }}'
  become: true
  when:
    - ansible_check_mode is false
    - docker_compose_start_stack | bool
