---
- name: Create configuration directory
  ansible.builtin.file:
    path: '/etc/samba'
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0755'
  become: true

- name: Create SMB credentials file
  ansible.builtin.copy:
    content: |
      username={{ backup.smb_share.username }}
      password={{ backup.smb_share.password }}
      domain={{ backup.smb_share.domain }}
    dest: '/etc/samba/backup.credentials'
    mode: '0600'
    owner: root
    group: root
  become: true
  no_log: true

- name: Mount SMB share on host
  ansible.posix.mount:
    path: "{{ backup.folder }}"
    src: "{{ backup.smb_share.path }}"
    fstype: cifs
    opts: "credentials=/etc/samba/backup.credentials,vers=3.0"
    state: mounted
  become: true
