---
authelia_stack_name: 'authelia'
authelia_config_folder: '{{ docker_config_dir }}/{{ authelia_stack_name }}'
authelia_docker_volumes:
  data: '{{ docker_volumes_dir }}/{{ authelia_stack_name }}/data'
  redis: '{{ docker_volumes_dir }}/{{ authelia_stack_name }}/redis'
