---
loki_stack_name: loki
loki_config_folder: '{{ docker_config_dir }}/{{ loki_stack_name }}'
loki_docker_volumes:
  data: '{{ docker_volumes_dir }}/{{ loki_stack_name }}/data'

loki_user:
  name: loki
  uid: 10001
  group: loki
  gid: 10001
