---
- name: Create Omada group
  ansible.builtin.group:
    name: omada
    gid: 508
    state: present
  become: true

- name: Create Omada user
  ansible.builtin.user:
    name: omada
    group: omada
    groups:
      - '{{ users.app_user.group }}'
    uid: 508
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    state: present
  become: true

- name: Add app user to Omada group
  ansible.builtin.user:
    name: "{{ users.app_user.name }}"
    groups:
      - omada
    append: true
  become: true

- name: Deploy Omada Controller
  ansible.builtin.include_role:
    name: docker_compose
  vars:
    docker_compose_stack_name: 'omada-controller'
    docker_compose_volumes: '{{ omada_controller_docker_volumes.values() }}'
    docker_compose_user_name: omada
    docker_compose_user_group: omada
