---
- name: Ensure Docker networks exist
  community.docker.docker_network:
    name: "{{ item }}"
    driver: bridge
    state: present
  loop:
    - "{{ monitoring.network_name }}"
    - "{{ traefik.network_name }}"
  become: true
