---
- name: Configure base system
  hosts: all
  tags:
    - setup
  tasks:
    - name: Configure system timezone
      community.general.timezone:
        name: "{{ system_timezone }}"
      become: true
      tags:
        - timezone
