---
- name: Deploy Healthchecks
  ansible.builtin.include_role:
    name: docker_compose
  vars:
    docker_compose_stack_name: '{{ healthchecks_stack_name }}'
    docker_compose_volumes: '{{ healthchecks_docker_volumes.values() }}'
    docker_compose_use_env: true

- name: Set up backup for healthchecks
  ansible.builtin.include_role:
    name: backup_cron
  vars:
    backup_cron_name: healthchecks
    backup_cron_data_path: "{{ healthchecks_docker_volumes.data }}"
    backup_cron_docker_compose_stack_name: "{{ healthchecks_stack_name }}"
    backup_cron_healthchecks_slug: "{{ backup.jobs.healthchecks.healthchecks_slug }}"
    backup_cron_hour: "{{ backup.jobs.healthchecks.hour }}"
    backup_cron_minute: "{{ backup.jobs.healthchecks.minute }}"
