---
- name: Deploy all dynamic configs
  ansible.builtin.template:
    src: "acquis/{{ item | basename }}"
    dest: "{{ crowdsec_docker_volumes.config }}/acquis.d/{{ item | basename | regex_replace('.j2$', '') }}"
    owner: '{{ users.app_user.name }}'
    group: '{{ users.app_user.group }}'
    mode: '0640'
  loop: "{{ query('fileglob', 'templates/acquis/*.yaml.j2') }}"
  become: true
  register: crowdsec_config_result

- name: Deploy CrowdSec
  ansible.builtin.include_role:
    name: docker_compose_stack
  vars:
    docker_compose_stack_name: '{{ crowdsec_stack_name }}'
    docker_compose_stack_volumes: '{{ crowdsec_docker_volumes.values() | list }}'
    docker_compose_stack_use_env: true
    docker_compose_stack_recreate: "{{ crowdsec_config_result.changed }}"
