---
healthchecks_stack_name: 'healthchecks'
healthchecks_config_folder: '{{ docker_config_dir }}/{{ healthchecks_stack_name }}'
healthchecks_docker_volumes:
  data: '{{ docker_volumes_dir }}/{{ healthchecks_stack_name }}/data'
