---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Restart Alloy
  ansible.builtin.systemd_service:
    name: alloy
    state: restarted
  become: true

- name: Restart smartctl exporter
  ansible.builtin.systemd_service:
    name: smartctl_exporter
    state: restarted
  become: true
