---
- name: Configure base system
  ansible.builtin.import_playbook: playbooks/base.yml

- name: Configure services hosts
  ansible.builtin.import_playbook: playbooks/services-host.yml

- name: Deploy services
  ansible.builtin.import_playbook: playbooks/services.yml
