---
# docker_compose_stack_name
# docker_compose_use_env: false
docker_compose_volumes: []

docker_compose_default_volume_mode: '0750'

# Whether to start the docker compose stack after deployment
docker_compose_start_stack: true
