---
- name: Create Loki group
  ansible.builtin.group:
    name: loki
    gid: 10001
    state: present
  become: true

- name: Create Loki user
  ansible.builtin.user:
    name: loki
    group: loki
    groups:
      - '{{ users.app_user.group }}'
    uid: 10001
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    state: present
  become: true

- name: Add app user to Loki group
  ansible.builtin.user:
    name: "{{ users.app_user.name }}"
    groups:
      - loki
    append: true
  become: true

- name: Create configuration directory
  ansible.builtin.file:
    path: '{{ loki_config_folder }}'
    state: directory
    owner: loki
    group: loki
    mode: '0750'
  become: true

- name: Copy configuration file
  ansible.builtin.copy:
    src: 'loki-config.yaml'
    dest: '{{ loki_config_folder }}/loki-config.yaml'
    owner: loki
    group: loki
    mode: '0640'
  become: true

- name: Deploy Loki
  ansible.builtin.include_role:
    name: docker_compose
  vars:
    docker_compose_stack_name: loki
    docker_compose_volumes: '{{ loki_docker_volumes.values() }}'
    docker_compose_user_name: loki
    docker_compose_user_group: loki
